name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:filter

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: Cypress Execution Report
         path: cypress/reports/html
         retention-days: 15

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: $
          publish_branch: gh-pages
          publish_dir: allure-history           
